# -*- coding: utf-8 -*-
"""Eva1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QZ-rA4TSPgSBDZqkYG-hOIuy7sEa4ZQz

# Implementación de Red Neuronal

## **1. Introducción**

El objetivo de este proyecto es implementar una red neuronal multicapa (MLP) para clasificar reseñas de películas en sentimientos positivos o negativos.

Se utilizará el dataset IMDB, el cual contiene reseñas de texto etiquetadas.

##**2. Carga de Datos**
En esta etapa se realiza la carga del dataset que será utilizado para el entrenamiento del modelo.

Se utiliza un archivo en formato CSV que contiene dos columnas principales:

- **review**: contiene las reseñas de texto de películas.
- **sentiment**: contiene la clasificación de cada reseña (positiva o negativa).

Para trabajar con los datos, se utiliza la librería **pandas**, que permite manipular estructuras de datos de manera eficiente.

Se carga el archivo mediante la función `read_csv`, lo que permite convertir el dataset en un DataFrame, facilitando su exploración y procesamiento posterior.

Posteriormente, se visualizan las primeras filas del dataset para verificar que los datos fueron cargados correctamente.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense, Input, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
import re

data = pd.read_csv("IMDB Dataset.csv")
display(data.head())

"""##**3. Exploración de Datos (EDA)**

En esta etapa se realiza un análisis exploratorio del dataset con el objetivo de comprender su estructura y características principales antes de entrenar el modelo.

Primero, se revisa la dimensión del dataset, observando la cantidad de registros y columnas disponibles. Esto permite tener una visión general del volumen de datos con el que se trabajará.

Posteriormente, se visualizan algunas filas del dataset para entender el contenido de las variables, confirmando que las reseñas están en formato de texto y que la variable objetivo corresponde al sentimiento asociado a cada reseña.

"""

print(f"Dimensiones del dataset: {data.shape}")

"""### Distribución de clases

Se analiza la distribución de la variable objetivo (`sentiment`) para verificar si el dataset está balanceado.

Los resultados muestran que existen:

- 25.000 reseñas positivas
- 25.000 reseñas negativas

Esto indica que el dataset está balanceado, lo cual es favorable para el entrenamiento del modelo, ya que evita sesgos hacia una clase específica.
"""

print("Distribución de clases de sentimiento:")
display(data['sentiment'].value_counts())

"""### Visualización

Se genera un gráfico de barras para representar la distribución de clases, lo que permite visualizar de manera clara el equilibrio entre ambas categorías.

Este análisis es importante, ya que un dataset desbalanceado puede afectar negativamente el desempeño del modelo.
"""

data['sentiment'].value_counts().plot(kind='bar')
plt.title("Distribución de clases (positivo vs negativo)")
plt.xlabel("Sentimiento")
plt.ylabel("Cantidad")
plt.show()

"""##**4. Preprocesamiento**

### Transformación de etiquetas
En esta etapa se realiza la transformación de la variable objetivo (`sentiment`) desde formato textual a formato numérico.

Originalmente, las etiquetas estaban representadas como:

- "positive"
- "negative"

Estas fueron convertidas a valores numéricos:

- 1 → positivo  
- 0 → negativo  

Esta transformación es necesaria, ya que los modelos de redes neuronales trabajan únicamente con datos numéricos, y no pueden procesar directamente variables categóricas en formato texto.

Posteriormente, se verifica la distribución de las clases luego de la transformación, confirmando que el dataset se mantiene balanceado:

- 25.000 ejemplos positivos  
- 25.000 ejemplos negativos  

El equilibrio en las clases es un aspecto importante, ya que evita que el modelo se incline hacia una categoría específica durante el entrenamiento, mejorando así la calidad de las predicciones.
"""

data['sentiment'] = data['sentiment'].map({
    'positive': 1,
    'negative': 0
})

print("Distribución de clases después de la transformación:")
display(data['sentiment'].value_counts())
print("El dataset se encuentra balanceado, con la misma cantidad de clases positivas y negativas.")

tokenizer = Tokenizer(num_words=5000)
X = tokenizer.texts_to_sequences(data['review'])
X = pad_sequences(X, maxlen=200)

"""Este paso forma parte del preprocesamiento de datos, siendo fundamental para asegurar una correcta entrada de información al modelo.

### Limpieza de Texto
En esta etapa se realiza una limpieza básica de las reseñas con el objetivo de mejorar la calidad de los datos de entrada.

Se aplicaron las siguientes transformaciones:

- Eliminación de etiquetas HTML presentes en el texto.
- Conversión de todo el texto a minúsculas.

Estas acciones permiten estandarizar los datos y evitar que el modelo considere diferencias irrelevantes, como mayúsculas o código HTML, lo que mejora el proceso de aprendizaje.
"""

def limpiar_texto(texto):
    texto = re.sub(r'<.*?>', '', texto)  # Eliminar etiquetas HTML
    texto = texto.lower()  # Convertir a minúsculas
    return texto

data['review'] = data['review'].apply(limpiar_texto)

"""### Preparación de Datos para Redes Neuronales (Tokenización y Padding)
Dado que las redes neuronales no pueden procesar texto directamente, es necesario transformar las reseñas en formato numérico.

Para ello, se aplicaron dos procesos principales:

#### Tokenización

Se utilizó un `Tokenizer` con un vocabulario máximo de 5000 palabras, el cual convierte cada palabra en un número entero.

Esto permite representar cada reseña como una secuencia de números, donde cada número corresponde a una palabra dentro del vocabulario más frecuente.

La limitación a 5000 palabras se realiza para reducir la complejidad del modelo y enfocarse en las palabras más relevantes del dataset.
"""

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(data['review'])

X = tokenizer.texts_to_sequences(data['review'])
X = pad_sequences(X, maxlen=200)

y = data['sentiment']

"""### División de Datos
Se dividió el dataset en conjunto de entrenamiento (80%) y prueba (20%) para evaluar la capacidad de generalización del modelo con datos no vistos.
Esta división permite medir la capacidad de generalización del modelo y evitar sobreajuste (overfitting).

Se utiliza `random_state=42` para asegurar la reproducibilidad de los resultados.
"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# y is already a pandas Series of 0s and 1s, so we just convert to numpy arrays.
y_train = y_train.values
y_test = y_test.values

print(f"Forma de X_train: {X_train.shape}")
print(f"Forma de X_test: {X_test.shape}")

"""## **5. Construcción del Modelo Base (MLP con Embedding)**

En esta etapa se implementa una red neuronal multicapa (MLP) para la clasificación de texto.

### Arquitectura del modelo

El modelo comienza con una capa **Embedding**, la cual permite transformar cada palabra en un vector numérico denso, capturando relaciones semánticas entre ellas.

Posteriormente, se utiliza una capa **Flatten** para convertir la salida de la capa Embedding en un vector plano, permitiendo su entrada a capas densas.

La arquitectura del modelo es la siguiente:

- **Embedding**: representación vectorial de palabras.
- **Flatten**: transformación a vector plano.
- **Dense (64 neuronas, ReLU)**: primera capa oculta.
- **Dense (32 neuronas, ReLU)**: segunda capa oculta.
- **Dense (1 neurona, Sigmoid)**: capa de salida para clasificación binaria.

### Funciones de activación

- **ReLU**: utilizada en las capas ocultas por su eficiencia computacional y capacidad de mejorar la convergencia del modelo.
- **Sigmoid**: utilizada en la capa de salida, ya que permite obtener una probabilidad entre 0 y 1 para clasificación binaria.

### Justificación del modelo

Se selecciona una arquitectura MLP debido a su simplicidad y capacidad de modelar relaciones no lineales. La incorporación de la capa Embedding permite mejorar la representación del texto en comparación con métodos más simples.
"""

model_base = Sequential([
    Embedding(input_dim=5000, output_dim=64),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

print("Resumen del Modelo Base:")
display(model_base.summary())

"""### Configuración del Modelo Base
El modelo fue configurado con los siguientes parámetros:

- **Optimizador**: Adam  
- **Tasa de aprendizaje**: 0.001  
- **Función de pérdida**: binary_crossentropy  
- **Métrica**: accuracy  

El optimizador Adam fue elegido debido a su capacidad de adaptar automáticamente la tasa de aprendizaje durante el entrenamiento, lo que mejora la convergencia del modelo.

La función de pérdida binary_crossentropy es adecuada para problemas de clasificación binaria, ya que mide la diferencia entre las predicciones del modelo y las etiquetas reales.
"""

model_base.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

"""##**6. Entrenamiento del Modelo Base**

El modelo fue entrenado utilizando los datos de entrenamiento previamente preparados.

### Configuración del entrenamiento

Se definieron los siguientes parámetros:

- **Número de épocas (epochs): 10**  
- **Tamaño de batch (batch size): 32**  
- **Validación: 20% del conjunto de entrenamiento**

El número de épocas determina cuántas veces el modelo recorre completamente el conjunto de datos. En este caso, se eligieron 10 épocas como un valor inicial para permitir al modelo aprender patrones sin aumentar excesivamente el tiempo de entrenamiento.

El tamaño de batch de 32 permite un equilibrio entre estabilidad en el entrenamiento y eficiencia computacional.

Se utilizó un **validation split de 0.2**, lo que significa que el 20% de los datos de entrenamiento se separan para validar el desempeño del modelo en cada época. Esto permite monitorear el aprendizaje y detectar posibles problemas como el sobreajuste (overfitting).

### Proceso de entrenamiento

Durante el entrenamiento, el modelo ajusta sus pesos internos para minimizar la función de pérdida, utilizando el optimizador Adam.

Se registran métricas como:

- **Accuracy**: porcentaje de predicciones correctas.
- **Loss**: error del modelo durante el entrenamiento.

Estas métricas serán utilizadas posteriormente para analizar el comportamiento del modelo.
"""

history_base = model_base.fit(
    X_train, y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

"""##**7. Evaluación del Modelo Base**

El modelo fue evaluado utilizando diversas métricas para obtener una visión completa de su desempeño en la tarea de clasificación.

### Métricas utilizadas

Se consideraron las siguientes métricas:

- **Accuracy**: proporción de predicciones correctas sobre el total.
- **Precision**: mide la proporción de predicciones positivas que son correctas.
- **Recall**: mide la capacidad del modelo para identificar correctamente los casos positivos.
- **F1-score**: media armónica entre precision y recall.

### Resultados obtenidos

El modelo alcanzó los siguientes resultados:

- Accuracy: 0.85  
- Precision: 0.86  
- Recall: 0.84  
- F1-score: 0.85  

Estos valores indican un buen desempeño general del modelo, con un equilibrio adecuado entre precisión y recall.
"""

y_pred_base = (model_base.predict(X_test) > 0.5).astype("int32")

print("Métricas de Evaluación del Modelo Base:")
print("Accuracy:", accuracy_score(y_test, y_pred_base))
print("Precision:", precision_score(y_test, y_pred_base, zero_division=0))
print("Recall:", recall_score(y_test, y_pred_base, zero_division=0))
print("F1-score:", f1_score(y_test, y_pred_base, zero_division=0))
print("\nReporte de Clasificación:")
print(classification_report(y_test, y_pred_base, zero_division=0))

"""### Análisis del reporte de clasificación

El reporte de clasificación muestra que el modelo tiene un rendimiento similar en ambas clases (positiva y negativa), lo cual es consistente con el hecho de que el dataset está balanceado.

No se observa un sesgo significativo hacia alguna de las clases, lo que indica que el modelo ha aprendido a diferenciar correctamente entre reseñas positivas y negativas.

### Análisis del Entrenamiento del Modelo Base
Los gráficos de accuracy y loss permiten observar el comportamiento del modelo durante el entrenamiento.

Se puede observar que:

- La precisión de entrenamiento y validación aumentan progresivamente, lo que indica que el modelo está aprendiendo correctamente.
- La pérdida (loss) disminuye a medida que avanzan las épocas, lo que refleja una mejora en el ajuste del modelo.
- No se observan diferencias significativas entre entrenamiento y validación, lo que sugiere que no existe sobreajuste (overfitting).

En general, el modelo presenta un entrenamiento estable y un buen nivel de generalización.

### Evolución de la precisión

El siguiente gráfico muestra cómo varía la precisión del modelo durante el entrenamiento y la validación.
"""

plt.plot(history_base.history['accuracy'])
plt.plot(history_base.history['val_accuracy'])
plt.legend(['Entrenamiento', 'Validación'])
plt.title("Evolución de la precisión del Modelo Base")
plt.xlabel("Épocas")
plt.ylabel("Accuracy")
plt.show()

"""### Evolución de la pérdida

El siguiente gráfico muestra cómo disminuye el error del modelo a medida que avanza el entrenamiento.
"""

plt.plot(history_base.history['loss'])
plt.plot(history_base.history['val_loss'])
plt.legend(['Entrenamiento', 'Validación'])
plt.title("Evolución de la pérdida del Modelo Base")
plt.xlabel("Épocas")
plt.ylabel("Loss")
plt.show()

"""## **8. Pruebas con Modelos Alternativos**

Con el objetivo de analizar el impacto de distintas configuraciones del modelo, se implementaron varias arquitecturas alternativas, modificando aspectos como el uso de Embedding, funciones de activación y técnicas de regularización.

Esto permitió evaluar cómo influyen estos cambios en el rendimiento del modelo.

### Modelo sin Embedding

Se implementó un modelo MLP sin la capa Embedding, utilizando directamente las secuencias numéricas como entrada.

Aunque se aumentó la cantidad de neuronas en las capas ocultas, este modelo no considera relaciones semánticas entre palabras, lo que limita su capacidad para trabajar con texto.
"""

model_mejorado = Sequential([
    Input(shape=(200,)), # Input directamente de las secuencias paddeadas
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])

model_mejorado.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_mejorado = model_mejorado.fit(
    X_train, y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

y_pred_mejorado = (model_mejorado.predict(X_test) > 0.5).astype("int32")

print("\nMétricas de Evaluación del Modelo Mejorado (sin Embedding):")
print("Accuracy:", accuracy_score(y_test, y_pred_mejorado))
print("Precision:", precision_score(y_test, y_pred_mejorado, zero_division=0))
print("Recall:", recall_score(y_test, y_pred_mejorado, zero_division=0))
print("F1-score:", f1_score(y_test, y_pred_mejorado, zero_division=0))
print("\nReporte de Clasificación:")
print(classification_report(y_test, y_pred_mejorado, zero_division=0))

"""#### Resultados

El modelo presentó un rendimiento bajo, con una accuracy cercana al 50%.

Esto indica que no logró aprender patrones relevantes, ya que tratar texto como números sin contexto no es adecuado para este tipo de problema.

### Modelo con función de activación Tanh

Se probó la función de activación Tanh en las capas ocultas, manteniendo la arquitectura sin Embedding.
"""

model_tanh = Sequential([
    Input(shape=(200,)),
    Dense(128, activation='tanh'),
    Dense(64, activation='tanh'),
    Dense(1, activation='sigmoid')
])

model_tanh.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_tanh = model_tanh.fit(
    X_train, y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

y_pred_tanh = (model_tanh.predict(X_test) > 0.5).astype("int32")

print("\nMétricas de Evaluación del Modelo con Tanh (sin Embedding):")
print("Accuracy:", accuracy_score(y_test, y_pred_tanh))
print("Precision:", precision_score(y_test, y_pred_tanh, zero_division=0))
print("Recall:", recall_score(y_test, y_pred_tanh, zero_division=0))
print("F1-score:", f1_score(y_test, y_pred_tanh, zero_division=0))
print("\nReporte de Clasificación:")
print(classification_report(y_test, y_pred_tanh, zero_division=0))

"""#### Resultados

El modelo con Tanh también presentó bajo rendimiento.

Esto puede explicarse por la saturación del gradiente, ya que Tanh tiende a perder capacidad de aprendizaje en redes profundas, afectando la convergencia del modelo.

### Modelo con Dropout

Se incorporó la técnica de regularización Dropout con una tasa de 0.3, con el objetivo de reducir el sobreajuste.
"""

model_dropout = Sequential([
    Input(shape=(200,)),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])

model_dropout.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_dropout = model_dropout.fit(
    X_train, y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

y_pred_dropout = (model_dropout.predict(X_test) > 0.5).astype("int32")

print("\nMétricas de Evaluación del Modelo con Dropout (sin Embedding):")
print("Accuracy:", accuracy_score(y_test, y_pred_dropout))
print("Precision:", precision_score(y_test, y_pred_dropout, zero_division=0))
print("Recall:", recall_score(y_test, y_pred_dropout, zero_division=0))
print("F1-score:", f1_score(y_test, y_pred_dropout, zero_division=0))
print("\nReporte de Clasificación:")
print(classification_report(y_test, y_pred_dropout, zero_division=0))

"""#### Resultados

El uso de Dropout no mejoró el rendimiento del modelo, sino que incluso lo redujo.

Esto sugiere que el problema principal no era el sobreajuste, sino la incapacidad del modelo para aprender correctamente sin una representación adecuada del texto.

## Comparación de modelos

| Modelo              | Embedding | Activación | Regularización | Accuracy |
|---------------------|----------|------------|---------------|----------|
| Modelo Base         | Sí       | ReLU       | No            | 0.85     |
| Sin Embedding       | No       | ReLU       | No            | 0.50     |
| Tanh                | No       | Tanh       | No            | 0.50     |
| Dropout             | No       | ReLU       | Sí            | 0.50     |

## Análisis de resultados

Los resultados muestran claramente que el uso de la capa Embedding tiene un impacto significativo en el rendimiento del modelo.

El modelo base (con Embedding) logró una accuracy del 85%, mientras que los modelos sin Embedding no superaron el 50%.

Esto demuestra que la representación semántica del texto es fundamental para tareas de procesamiento de lenguaje natural.

Además, cambios en funciones de activación y técnicas de regularización no lograron mejorar el rendimiento cuando la representación de entrada no era adecuada.

## Ejemplos de predicción

Se presentan ejemplos de predicciones utilizando el modelo base, con el objetivo de ilustrar su funcionamiento en datos nuevos.
"""

def predict_sentiment(review_text):
    # Limpiar el texto de la reseña
    cleaned_review = limpiar_texto(review_text)
    # Convertir el texto a secuencia numérica usando el tokenizer entrenado
    sequence = tokenizer.texts_to_sequences([cleaned_review])
    # Aplicar padding para que tenga la misma longitud que los datos de entrenamiento
    padded_sequence = pad_sequences(sequence, maxlen=200)
    # Realizar la predicción con el modelo base
    prediction = model_base.predict(padded_sequence)[0][0]

    sentiment = 'Positivo' if prediction > 0.5 else 'Negativo'
    return sentiment, prediction

# Ejemplos de predicciones
review1 = "This movie was absolutely fantastic! I loved every minute of it."
sentiment1, prob1 = predict_sentiment(review1)
print(f"Reseña: '{review1}'\nSentimiento predicho: {sentiment1} (Probabilidad: {prob1:.4f})\n")

review2 = "What a terrible film. I wasted two hours of my life."
sentiment2, prob2 = predict_sentiment(review2)
print(f"Reseña: '{review2}'\nSentimiento predicho: {sentiment2} (Probabilidad: {prob2:.4f})\n")

review3 = "It was okay, not great, not bad, just average."
sentiment3, prob3 = predict_sentiment(review3)
print(f"Reseña: '{review3}'\nSentimiento predicho: {sentiment3} (Probabilidad: {prob3:.4f})\n")

"""## **9. Comparación Final de Modelos**

Con el objetivo de analizar el desempeño de las distintas configuraciones implementadas, se realizó una comparación de métricas entre los modelos evaluados.

Se consideraron las siguientes métricas:

- Accuracy
- Precision
- Recall
- F1-score

Estas métricas permiten evaluar de manera integral el comportamiento del modelo en tareas de clasificación.
"""

modelos = ['Modelo Base (Embedding)', 'Modelo Mejorado (s/ Emb)', 'Modelo con Tanh (s/ Emb)', 'Modelo con Dropout (s/ Emb)']
accuracy_scores = [accuracy_score(y_test, y_pred_base), accuracy_score(y_test, y_pred_mejorado), accuracy_score(y_test, y_pred_tanh), accuracy_score(y_test, y_pred_dropout)]
precision_scores = [precision_score(y_test, y_pred_base, zero_division=0), precision_score(y_test, y_pred_mejorado, zero_division=0), precision_score(y_test, y_pred_tanh, zero_division=0), precision_score(y_test, y_pred_dropout, zero_division=0)]
recall_scores = [recall_score(y_test, y_pred_base, zero_division=0), recall_score(y_test, y_pred_mejorado, zero_division=0), recall_score(y_test, y_pred_tanh, zero_division=0), recall_score(y_test, y_pred_dropout, zero_division=0)]
f1_scores = [f1_score(y_test, y_pred_base, zero_division=0), f1_score(y_test, y_pred_mejorado, zero_division=0), f1_score(y_test, y_pred_tanh, zero_division=0), f1_score(y_test, y_pred_dropout, zero_division=0)]

x = np.arange(len(modelos))

plt.figure(figsize=(12, 6))
plt.bar(x - 0.2, precision_scores, width=0.2, label='Precision')
plt.bar(x, recall_scores, width=0.2, label='Recall')
plt.bar(x + 0.2, accuracy_scores, width=0.2, label='Accuracy')

plt.xticks(x, modelos, rotation=45, ha='right')
plt.title("Comparación de métricas por modelo")
plt.legend()
plt.tight_layout()
plt.show()

"""## Análisis comparativo de modelos

Los resultados obtenidos evidencian diferencias significativas entre los modelos evaluados.

El **Modelo Base (con Embedding)** presenta el mejor desempeño, alcanzando una accuracy cercana a 0.85, junto con un equilibrio adecuado entre precision y recall. Esto indica que el modelo logra identificar correctamente ambas clases sin sesgo significativo.

En contraste, los modelos que no incorporan la capa Embedding (Modelo Mejorado, Tanh y Dropout) presentan un rendimiento considerablemente menor, con métricas cercanas al 50%, lo que equivale a un comportamiento similar al azar.

Esto demuestra que la representación del texto es un factor crítico en el desempeño del modelo. La capa Embedding permite capturar relaciones semánticas entre palabras, lo que resulta fundamental en tareas de procesamiento de lenguaje natural.

Por otro lado, modificaciones como el cambio de función de activación (Tanh) o la aplicación de técnicas de regularización (Dropout) no lograron mejorar el rendimiento en ausencia de una representación adecuada del texto.

## **10. Conclusión General**

En este trabajo se implementó una red neuronal multicapa (MLP) para resolver un problema de clasificación de texto, evaluando distintas configuraciones del modelo.

Los resultados obtenidos permiten concluir que:

- La incorporación de una capa Embedding es fundamental para el procesamiento de texto.
- Las redes MLP presentan limitaciones cuando no se utiliza una representación adecuada de los datos de entrada.
- El ajuste de hiperparámetros como funciones de activación y regularización no compensa una mala representación del texto.

El modelo base logró un buen desempeño, evidenciando la importancia de transformar correctamente los datos antes de entrenar la red neuronal.

Como mejora futura, se recomienda el uso de modelos más avanzados orientados a datos secuenciales, tales como:

- Redes Neuronales Recurrentes (RNN)
- Long Short-Term Memory (LSTM)
- Transformers

Estos modelos permiten capturar el contexto y la dependencia entre palabras, lo que podría mejorar significativamente el rendimiento en tareas de clasificación de texto.
"""